FROM python:3.8.14-slim as base

RUN pip install pipenv

WORKDIR /base

COPY Pipfile Pipfile.lock /base/

RUN pipenv requirements > requirements.txt


FROM python:3.8.14-slim as prod

RUN apt-get update -y && \
    apt-get install -y --no-install-recommends  \
    build-essential \
    python3-dev \
    python3-pip \
    python3-wheel \
    python3-setuptools && \
    rm -rf /var/lib/apt/lists/* /var/cache/apt/archives/*

RUN pip3 install --no-cache-dir --upgrade setuptools pip wheel

WORKDIR /app

COPY --from=base /base/requirements.txt requirements.txt

RUN pip3 install -r requirements.txt

COPY boaviztapi boaviztapi

EXPOSE 5000
ENTRYPOINT ["uvicorn", "boaviztapi.main:app", "--host", "0.0.0.0", "--port", "5000", "--reload"]
