name: Publish branch specific docker image

on:
  push:
    branches:
      - 'greenhack22'

jobs:

  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      
      - name: Install pipenv
        run: |
            python -m pip install --upgrade pipenv wheel
      
      - id: cache-pipenv
        uses: actions/cache@v1
        with:
          path: ~/.local/share/virtualenvs
          key: ${{ runner.os }}-pipenv-${{ hashFiles('**/Pipfile.lock') }}
      
      - name: Install dependencies
        if: steps.cache-pipenv.outputs.cache-hit != 'true'
        run: |
          pipenv install --dev
      
      - name: Build the pip package
        run: python3 setup.py sdist
      
      - name: Build the api Docker image
        run: docker build --build-arg VERSION=$(python setup.py --version) . --file Dockerfile --tag ghcr.io/boavizta/boaviztapi:greenhack22
      
      - name: Push api images
        run: docker push ghcr.io/boavizta/boaviztapi:greenhack22
      
      - name: Build doc the Docker image
        run: docker build docs --file docs/Dockerfile --tag ghcr.io/boavizta/boaviztapi-doc:greenhack22
      
      - name: Push doc images
        run: docker push ghcr.io/boavizta/boaviztapi-doc:greenhack22
